### ISSUE TITLE
eShop spoofing no longer works

### ISSUE THREAD

**Issue by Jdbye** [hartmannaf/Free-multi-Patcher#10]
eShop spoofing no longer works after a recent change Nintendo made.
eShop loads and appears to work until you tap on an item and it shows "An error has occurred."
This is bad news for us n3DS owners, so I hope you can figure out what Nintendo changed in 10.0.0 that broke spoofing on lower firmwares.

**Comment by Hartie95** [comment]
Nintendo changed some urls, this is a little change, but it is not possible to patch this inside of FMP currently.
Hans or NTR is currently needed, but a goal for later is to create something that runs in the background(like NTR) or replaces an applet. But this is a long time goal, which I'm not able to archive in the next time.

**Comment by Hartie95** [comment]
Now with firmlaunch 10.2 for old and new 3ds its possible to use the latest version of tiger, together with FMP on any firmware.

**Comment by Jdbye** [comment]
Forgot about this app for a while, but now that ctr-httpwn exists, has anything changed? Should it not be possible to patch the HTTP sysmodule the same way ctr-httpwn does, maybe by using that code as a base, since it's open source? It may not be of much use to most people anymore but I'm sure all of us Gatewaiters would like a faster way to patch online rather than booting into HBL every time.
