### ISSUE TITLE
Create a Patchlayout, to allow variable patch loading from SD-card.

### ISSUE THREAD

**Issue by Hartie95** [hartmannaf/Free-multi-Patcher#2]
Like @Syphurith and @dukesrg mentiont in https://github.com/roxas75/rxTools/issues/80 and in https://github.com/hartmannaf/rxTools/commit/89be273dc2240771f4556d01f56dd02bbcb86f24 a patch layout should be defined, and a easy/variable way to add/remove patches should be implemented.

I think it should be a binary layout, because I would like to add this ability after implementation to rxTools to, and its not easy to do much converting in rxtools patching thread for arm11(It will not work if the thread binary it to big).

Because I would like to allow to use all patches from arm9(rxTools) and arm11 Applications(Free Multi Patcher) we will need 2 start addresses for every patch(one from inside the process Memory, and with the real address) and a search area.
Also we need the original Code, and the patchcode together with there size. 
Maybe for the future a max/min system version would be usefull, because it could be possible that some patches wont work on older/newer firmware versions.

**Comment by dukesrg** [comment]
Patch may contain a flag word with feature definitionls at least:
- Mode ARM9/ARM11
- patch from MyThread (or is it the same as ARM11?)
- sysNAND compatible
- emuNAND compatible
- firmware versions, including all regions (maybe this one will occupy several bytes because needx versions*regions bits)
- ?
  Must alse reserve space for future use/version extension or just make it variable length

**Comment by Hartie95** [comment]
At the moment it will only be patches for arm 11, but we could implement a mode value(should be usefull later).
The addresses should only be start addresses, were the search begins. also there should be a search area, because otherwise we will need to define the addresses for every system version. But for patching from fmp we will use the address within the process memory, because its easier to know. For patching from arm9 on the other side we will need to know the absolute address. For this we could create a list, that shows where each process starts.
The emunand flag could also be usefull(at least for arm9 patches). Maybe this could be a short, wich defines sys&emunand, sysnand only, emunand only.
I think the regions sytem modules and applications should not be to different, so I dont know if its needed, but the firmware/system verion should be included.
The Version is a good idea, but it should be the first byte, so its easier read it.

**Comment by Hartie95** [comment]
@Syphurith and @dukesrg
I think the struct for the patches should look somthing like this:

``` C
struct patch
{
    short version;
    short patchNameSize;
    short descriptionSize;
    short processNameSize
    short originalcodeSize;
    short patchcodeSize;
    short patchType;
    u32 minKernelVersion;
    u32 maxKernelVersion;
    short nandCompability;
    u32   startAddressProcess;
    u32   startAddressGlobal;
    u32   searchAreaSize;
    char  binaryData[];
}
```

I don't know, if u32 is big enough to show the kernel version. What so you think about this layout?

**Comment by dukesrg** [comment]
Isn't ARM code slower for shorts?

**Comment by Hartie95** [comment]
@dukesrg Could be possible, but it should not make a big difference(we could cast it to int before we start working with them). But every patch file will be 24 Bytes bigger if we use u32/int instead of short.

**Comment by dukesrg** [comment]
@hartmannaf
Not sure if min/max kernel versio nwill be enough because if different versions and regions may be using the same kerne lversion but still require another patch (or nor?)

**Comment by Hartie95** [comment]
@dukesrg Is there any region spezific code(exept for the Text strings) that is different between the versions? The possible offset difference is unimportent, because we search for the position, but we could add a region field. Is it possible to get the region from arm9? 

the region then should be something like this:

``` C
char  regionsSupported[7];
```

where the id are:
1 Japan 
2 North America
3 Europe 
4 Australia 
5 China
6 Korea
7 Taiwan   

(Maybe without Australia, because its unused)

**Comment by dukesrg** [comment]
@hartmannaf I think bit-field will be enough

**Comment by Hartie95** [comment]
@dukesrg You are right. than the region will be something like this:

``` C
struct regionsStruct
{
    unsigned int Japan:1;
    unsigned int NorthAmerica:1;
    unsigned int Europe:1;
    unsigned int Australia:1;
    unsigned int China:1;
    unsigned int Korea:1;
    unsigned int Taiwan :1;
}regions;

struct patch
{
 ...
    regions regionssupported;
 ...
};
```

**Comment by dukesrg** [comment]
@hartmannaf something like that. In case there will be no region&version differences at the same time

**Comment by Syphurith** [comment]
The structure is almost ok for me.
However i don't know if you would need to "override" sometimes. I mean when certain offset content should be just overrided by the patch instead of testing its actual content.
You could replace most of those `short`s to `u32`.

**Comment by Hartie95** [comment]
@Syphurith and @dukesrg  
I will implement and test something like this, but its not the final version 0:

``` C
typedef struct regionsStruct
{
    unsigned int japan:1;
    unsigned int northAmerica:1;
    unsigned int europe:1;
    unsigned int australia:1;
    unsigned int china:1;
    unsigned int korea:1;
    unsigned int taiwan :1;
    unsigned int filler :1;
} regions;

typedef struct patchStruct
{
    short   version;
    short   patchNameSize;
    short   descriptionSize;
    short   processNameSize;
    short   originalcodeSize;
    short   patchcodeSize;
    short   processType;            //here we could use the firmware types from http://3dbrew.org/wiki/FIRM
    u32     minKernelVersion;  
    u32     maxKernelVersion;
    regions regionsSupported;
    short   nandCompability;        //could also be a struct to define possible different types for future
    short   patchType;              //0->search code, 1->overwrite code, 2->search String, 3->overwrite string 
    u32     startAddressProcess;    //or patch address for overwrite
    u32     startAddressGlobal;     //same as the above
    u32     searchAreaSize;         //0 for overwrite mode
    u32     numberOfReplacements;   //0->overwrite all apearences inside area
    const char binaryData[];        //order: patchName,description,processname,OriginalCode,patchBegin
} patch;
```

Like I said, its not final, so it could still be changed, while I implement the first version in fmp, so dont implement it now. 
Also I will replace most of the shorts to u32 like @Syphurith said.
After the layout is final, I will create a wiki page explaining the format, and create a simple tool for creating the patch files. 
Till then anybody could still discuss about it here.

**Comment by Syphurith** [comment]
the patch layout LGTM, except `char`->`u8`, `short`->`u16`. However those `u32` or else is just a naming problem, not a real issue. So lucky you could ignore thus if not feeling easy.

**Comment by Hartie95** [comment]
so here the branch were I will push my progress on implementing the patchlayout:
https://github.com/hartmannaf/Free-multi-Patcher/tree/patchLayout

At the moment im able to load patchfiles and apply them, but its still more dirty testing code than anything releasable. I also need to rewrite the menu generation, to load the information from inside the patch files, and find a way to identify them to allow disabeling and enabeling them.
Also some other work like the string replacing and the direct overwrite mode need to be implemented.

Still it should be implemented somewhere outside of free multi patcher, because the format could still be changed.

**Comment by Hartie95** [comment]
For patches outside of the kernel modules, I should also add the min and max firmware version to the layout. 
I'm rewriting a lot of the free multi patcher at the moment, to make it more variable, so the final version of the layout could need a bit more time.

**Comment by Hartie95** [comment]
@Syphurith and @dukesrg I created some Issues for some things I need to discuss. ( #4  #5  #6 )
Also I created a wiki page for the [patchlayout](https://github.com/hartmannaf/Free-multi-Patcher/wiki/patchlayout) were I will add changes to the layout while development and add some descriptions.

**Comment by Hartie95** [comment]
@mid-kid and @b1l1s What are you thinking about this [patchlayout](https://github.com/hartmannaf/Free-multi-Patcher/wiki/patchlayout) as simple binary patch layout?
I will try to add something to allow collections of patches(regionfree could need that for example), but I have no correct idea how I will implement them at the moment.

**Comment by mid-kid** [comment]
You should work on the format as you implement it. That way, it'll be clear to you what you need or not.
I can see a few fields of questionable usability:
- version
- patchNameSize (Some people prefer using strlen())
- originalCodeSize (Depends on the implementation. Dunno what you're trying to do)
- minKernelVersion and maxKernelVersion (If things really depend on the kernel version, they usually don't support more than one version.)

You could also use some existing relocateable ELF format, though I don't know the specifics.

**Comment by Hartie95** [comment]
@mid-kid version is for possible future additions and changes in the patch layout.
the sizes are used to get the size and positions inside of the binary part, but with using '\0' it should be possible to get them using strlen, at least for the strings.
The originalCode and originalCodeSize is used for searching for a code segment, which then will be replaced by the patchCode.
While using addresses it could be possible that it only supports one kernel version, but when searching for code it could support multiple kernel versions. 
I would also like to add a min and max firmware version field, because some patches could depend on the firmware version instead of the kernel version(like home menu patches).
The patchlayout branch of my patcher shows the current implementation of the layout.
At the moment it is planed to use it for all simple patches, like patched return values, simple menu patches, e-shop spoof or serial patching.

**Comment by mid-kid** [comment]
@hartmannaf Thanks for explaining. It looks fine to me. Collections of patches could just be arrays, either with some delimiter at the end and loop through them, or with a count in the header. You will probably want to separate the "global" header and the "per-patch" header. Here is the [.cake format](https://github.com/mid-kid/CakesForeveryWan/blob/master/patches/header.txt) for example.

**Comment by Hartie95** [comment]
@mid-kid Thanks for the feedback, its a good Idea to have patchcollections with an header, in collections a names and descriptions will not be needed for every patch, but maybe a optional description and name will still be usefull, to allow to port them to newer firmware or kernel versions, or to find bugs if somethings breaks things. So it would be easier to disable single elements, but these would be more usefull for creation, debuging and testing of patches.

Also one thing I need to find out is, how to save user selections for enabling and disabling of patches,
but thats an optional feature at the moment. I have something in mind, but I need to let it be variable, because the user could add and remove patches.

**Comment by Hartie95** [comment]
I now implemented a first version of [patch collections](https://github.com/hartmannaf/Free-multi-Patcher/wiki/patchCollectionlayout).
The implementation could be seen in the patchLayout branch.
Also I added a new offset field to the [patchlayout](https://github.com/hartmannaf/Free-multi-Patcher/wiki/patchlayout)

**Comment by Hartie95** [comment]
I now updated the wikipages([patch collections](https://github.com/hartmannaf/Free-multi-Patcher/wiki/patchCollectionlayout), [patchlayout](https://github.com/hartmannaf/Free-multi-Patcher/wiki/patchlayout) )
 to show the current state.
I also added some descriptions and definition for some fields.

**Comment by Hartie95** [comment]
I think the layout is nearly completed, but I haven't tested all types of patches I had implemented, so the beta Users have to test it.
