### ISSUE TITLE
Implement all types of patches

### ISSUE THREAD

**Issue by Hartie95** [hartmannaf/Free-multi-Patcher#5]
We need to discuss what types of patches we are need.
Also we need to know what informations we need to know for these types.
I think about:
- Find and replace -> binary
  - startAddress
  - searchArea
  - originalcode
  - patchcode
  - maybe offset
- Overwrite at -> binary
  - address
  - patchcode
  - maybe offset
  - maybe originalcode for an revert patch ability
- Find and replace -> string
  - startAddress
  - searchArea
  - originalstring
  - patchstring
  - string shift
  - maybe offset
- Overwrite at -> string
  - address
  - patchstring
  - string shift
  - maybe offset
  - maybe originalstring for an revert patch ability

**Comment by Syphurith** [comment]
If you've checked the present from gbatemp ago.. You would know there is some dynamic pointers.
I don't know if just static address could serve us well.. Maybe a patch script, or relative one in process.
That may be difficult for you now, and not forever.. You could find more guys to talk about this..

**Comment by Hartie95** [comment]
I haven't had the time to check it, but these are the simple patches, that should be possible at the moment, one thing I think about are patch collections. Because there are multiple patches needed to apply for some things(like real regionfree: menu for showing them, ns for ignoring out of region updates).
I will create a issue for this later, first the current issues are more important.

**Comment by Syphurith** [comment]
@hartmannaf ~~ns for out-of-region update? I only know it may be the cfg that need to be patched for out-of-region dlc.~~ And that is dynamically patched, through pointers.
BTW I think you may even contact cakesfw group. Cake is patch for them.

Edit: I would be wrong. Didn't find any 0x10082 in the binary of cfg module when following the function.

**Comment by Hartie95** [comment]
I now Implemented these 6 types of patches(all the new ones are untested)

0 -> findAndReplaceCode
1 -> replaceCodeAt
2 -> usePointerAndReplaceCode
3 -> findAndReplaceString
4 -> replaceStringAt
5 -> usePointerAndReplaceString

while the patchOffset will be added to the target address in the patches having a code type, the offset will set the size between each one of the characters. to be written.

**Comment by Hartie95** [comment]
All types are implemented now, but not all of them are tested.

**Comment by Hartie95** [comment]
The future will show if there are any problems with the implementations on FMP, I close this for now.
